title: Neighborhood Case Study
description: Case study for the development of Neighborhood
theme: just-the-docs

url: https://neighborhood-app.github.io

aux_links:
  App Repository: https://github.com/neighborhood-app/app
