title: Neighborhood Case Study
description: Case study for the development of Neighborhood
theme: just-the-docs

url: https://neighborhood-app.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
